apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-dep
  labels:
    name: flask-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-dep
    spec:
      containers:
      - name: docker-flask-con
        image: docker-flask:latest
        imagePullPolicy: Never
